import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer'
import Toolbar from '../components/toolbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>News App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='page-container'>
        <Toolbar />
        <div className={styles.main}>
          <h1>Bulgarian News App</h1>
          <h3>Your one stop away from the latest news articles</h3>
          <Image className={styles.image}
            src='/newsfront.jpg'
            alt='Front news'
            width={250}
            height={250}
          />
        </div>
      </div>
      <Footer />
    </div>
  )
}
